#!/usr/bin/env sh

# 使用font-awesome替代罗马数字
# yabai -m config status_bar_space_icon_strip                8 9 

spacebar -m config position           top
spacebar -m config height             26
# spacebar -m config spacing_left       25
# spacebar -m config spacing_right      15
# spacebar -m config text_font          "Helvetica Neue:Bold:18.0"
spacebar -m config text_font          "Hack Nerd Font Mono:Bold:18.0"
spacebar -m config icon_font          "Hack Nerd Font Mono:Regular:25.0"
spacebar -m config background_color   0xff202020
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config space_icon_color   0xff458588
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config battery_icon_color 0xffd75f5f
spacebar -m config dnd_icon_color     0xffa8a8a8
spacebar -m config clock_icon_color   0xffa8a8a8
spacebar -m config space_icon_strip             
spacebar -m config power_icon_strip      # 
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%d/%m/%y %R"

echo "spacebar configuration loaded.."
