#!/usr/bin/env sh

gaps_top="30"
gaps_bottom="10"
gaps_left="10"
gaps_right="10"
gaps_inner="10"


# bar settings
# 打开状态栏
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
# 使用font-awesome替代罗马数字
yabai -m config status_bar_space_icon_strip                8 9  
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          1
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize


yabai -m config layout                       bsp
# general space settings(设置间隔)
yabai -m config top_padding                  "${gaps_top}"
yabai -m config bottom_padding               "${gaps_bottom}"
yabai -m config left_padding                 "${gaps_left}"
yabai -m config right_padding                "${gaps_right}"
yabai -m config window_gap                   "${gaps_inner}"

# 临时性的 App 也就是 manage=off 不受到 yabai 平铺式的限制，之前怎么弹出来就怎么弹出来
otherApp='^(访达|Finder|Calendar|日历|System Preferences|系统偏好设置|1Password 7|Mail|微信|WeChatc|QQ|Google Chrome|IINA|Visual Studio Code|OBS)$'
yabai -m rule --add app="${otherApp}" manage=off

echo "yabai configuration loaded.."
