
# source ~/.config/zsh/mappings.zsh
#
# if [ -f ~/.sconfig/zsh/zshrc ]; then
#     source ~/.sconfig/zsh/zshrc
# fi
#

source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/others.zsh
source ~/.config/zsh/zim-plugin.zsh

